In [1]:
import pandas as pd
import tqdm.auto as tqdm
import os

c:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
act_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/act_key.csv")

cases_court_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/cases_court_key.csv")

cases_district_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/cases_district_key.csv")

cases_state_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/cases_state_key.csv")

disp_name_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/disp_name_key.csv")

judge_case_merge_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/judge_case_merge_key.csv")

purpose_name_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/purpose_name_key.csv")

section_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/section_key.csv")

type_name_key = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/keys/type_name_key.csv")

judges_clean = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Projects/Judicial_DA/data/justice_data/csv/judges_clean.csv")

# Removing unnecessary tables

### act_key - dropping entire pipeline

In [4]:
del act_key

### section_key - dropping entire pipeline

In [5]:
del section_key

# Removing unnecessary columns

### disp_name_key - dropping count column

In [6]:
del disp_name_key['count']

In [7]:
disp_name_key

     year  disp_name  disp_name_s
0    2010          1     258 crpc
1    2010          2       abated
2    2010          3    absconded
3    2010          4    acquitted
4    2010          5      allowed
..    ...        ...          ...
457  2018         48       stayed
458  2018         49  transferred
459  2018         50  uncontested
460  2018         51      untrace
461  2018         52    withdrawn

[462 rows x 3 columns]

In [8]:
disp_name_key[disp_name_key['disp_name_s'] == 'acquitted']

     year  disp_name disp_name_s
3    2010          4   acquitted
54   2011          4   acquitted
105  2012          4   acquitted
156  2013          4   acquitted
207  2014          4   acquitted
258  2015          4   acquitted
309  2016          4   acquitted
361  2017          4   acquitted
413  2018          4   acquitted

### purpose_name_key - dropping count column

In [9]:
purpose_name_key

,year,purpose_name,purpose_name_s,count
0,2010,NaN,NaN,254130
1,2010,1.0,'b' f/r report,2
2,2010,2.0,'p' hearing,1
3,2010,3.0,(10am to 1pm ...,131
4,2010,4.0,(2pm to 5pm ...,58
...,...,...,...,...
68120,2018,8266.0,ws nfl hearing,1
68121,2018,8267.0,ws obj to ia,28
68122,2018,8268.0,ws of respondent,9
68123,2018,8269.0,ws/ objection,1009
68124,2018,8270.0,ws/wo,6

means 26,47,896 cases do not have 'purpose_name' mentioned (null)

In [10]:
purpose_name_key[purpose_name_key['purpose_name'].isna()]['count'].sum()

np.int64(2647896)

means 7,82,88,048 cases have 'purpose_name' mentioned

In [11]:
purpose_name_key[purpose_name_key['purpose_name'].notna()]['count'].sum()

np.int64(78288048)

In [12]:
del purpose_name_key['count']

### type_name_key -

In [13]:
type_name_key.sort_values('count', ascending=False)

       year  type_name     type_name_s   count
56157  2018      977.0              cc  900758
48605  2017      981.0              cc  899445
41170  2016      929.0              cc  895703
33719  2015      956.0              cc  787564
26503  2014      915.0              cc  766294
...     ...        ...             ...     ...
43136  2016     2895.0  factories act.       1
23586  2013     5088.0  pocso act 2012       1
15429  2012     3749.0  mat. execution       1
15426  2012     3746.0       mat. apl.       1
62702  2018     7522.0         xxxxxos       1

[62714 rows x 4 columns]

In [14]:
del type_name_key['count']

In [15]:
type_name_key

       year  type_name          type_name_s
0      2010        1.0             (m) t.s.
1      2010        2.0                 (sc)
2      2010        3.0           ..mact 166
3      2010        4.0   04 complaint cases
4      2010        5.0     04 criminal case
...     ...        ...                  ...
62709  2018     7529.0      xxxxxspl t.ndps
62710  2018     7530.0   zila panchayat act
62711  2018     7531.0  zilla panchayat act
62712  2018     7532.0     zima 457 cr.p.c.
62713  2018     7533.0    zimma application

[62714 rows x 3 columns]

In [41]:
type_name_key['type_name'] = type_name_key['type_name'].astype('Int64')

### cases_court_key - NO CHANGE

In [16]:
cases_court_key.head(1)

,year,state_code,state_name,district_name,dist_code,court_no,court_name
0,2010,1,Maharashtra,Nandurbar,1,1,Chief Judcial Magistrate Nandurbar

In [40]:
len(cases_court_key)

59428

### cases_district_key - remove (pc11_state_name, pc11_state_id, pc11_district_name, pc11_district_id)

In [17]:
cases_district_key.head(1)

,year,state_code,state_name,dist_code,district_name,pc11_state_name,pc11_state_id,pc11_district_name,pc11_district_id
0,2010,2,Andhra Pradesh,7,Kadapa,andhra pradesh,28,NaN,NaN

In [18]:
del cases_district_key['pc11_state_name']
del cases_district_key['pc11_state_id']
del cases_district_key['pc11_district_name']
del cases_district_key['pc11_district_id']

In [19]:
cases_district_key.head(1)

   year  state_code      state_name  dist_code district_name
0  2010           2  Andhra Pradesh          7        Kadapa

### cases_state_key - remove (pc11_state_name, pc22_state_id)

In [20]:
del cases_state_key['pc11_state_name']
del cases_state_key['pc11_state_id']

In [21]:
cases_state_key

     year  state_code      state_name
0    2018           2  Andhra Pradesh
1    2011           2  Andhra Pradesh
2    2011          29       Telangana
3    2010          29       Telangana
4    2014           2  Andhra Pradesh
..    ...         ...             ...
282  2010          16     West Bengal
283  2017          16     West Bengal
284  2013          16     West Bengal
285  2014          16     West Bengal
286  2015          16     West Bengal

[287 rows x 3 columns]

### judge_case_merge_key - NO CHANGE

In [22]:
judge_case_merge_key

                       ddl_case_id  ddl_filing_judge_id  ddl_decision_judge_id
0         01-01-01-201900000022018                  5.0                    5.0
1         01-01-01-201900000032017                  5.0                    5.0
2         01-01-01-201900000032018                 94.0                   94.0
3         01-01-01-201900000042016                  3.0                    5.0
4         01-01-01-201900000042018                156.0                  156.0
...                            ...                  ...                    ...
12901141  30-02-06-203500000292016                  NaN                98408.0
12901142  30-02-06-203500000302016                  NaN                98427.0
12901143  30-02-06-203500000322016                  NaN                98462.0
12901144  30-02-06-203500000342016                  NaN                98427.0
12901145  30-02-06-203600001332016                  NaN                98408.0

[12901146 rows x 3 columns]

checking whether ddl_filing_judge_id is having values like 5.6 or not - ANSWER IS NOT... means.. it's same as ddl_judge_id

In [23]:
judge_case_merge_key[judge_case_merge_key['ddl_filing_judge_id']%1 != 0]

                       ddl_case_id  ddl_filing_judge_id  ddl_decision_judge_id
10936177  01-01-01-201900000062016                  NaN                   94.0
10936178  01-01-01-201900000442016                  NaN                   94.0
10936179  01-01-01-201900000672016                  NaN                   94.0
10936180  01-01-01-201900000882016                  NaN                   94.0
10936181  01-01-01-201900001112016                  NaN                   94.0
...                            ...                  ...                    ...
12901141  30-02-06-203500000292016                  NaN                98408.0
12901142  30-02-06-203500000302016                  NaN                98427.0
12901143  30-02-06-203500000322016                  NaN                98462.0
12901144  30-02-06-203500000342016                  NaN                98427.0
12901145  30-02-06-203600001332016                  NaN                98408.0

[1964969 rows x 3 columns]

### judges_clean

In [24]:
judges_clean

,ddl_judge_id,state_code,dist_code,court_no,judge_position,female_judge,start_date,end_date
0,1,1,1,1,chief judicial magistrate,0 nonfemale,20-09-2013,20-02-2014
1,2,1,1,1,chief judicial magistrate,0 nonfemale,31-10-2013,20-02-2014
2,3,1,1,1,chief judicial magistrate,0 nonfemale,21-02-2014,31-05-2016
3,4,1,1,1,chief judicial magistrate,0 nonfemale,01-06-2016,06-06-2016
4,5,1,1,1,chief judicial magistrate,0 nonfemale,06-06-2016,07-07-2018
...,...,...,...,...,...,...,...,...
98473,98474,30,2,9,criminal cases,1 female,21-04-2004,14-11-2013
98474,98475,30,2,9,criminal cases,1 female,16-01-2015,16-01-2016
98475,98476,30,2,9,criminal cases,1 female,09-12-2016,31-07-2017
98476,98477,30,2,10,criminal cases,1 female,15-05-2017,28-01-2019
98477,98478,30,2,10,criminal cases,0 nonfemale,28-01-2019,NaN

# Formatting columns where needed

### 1. Converting judge IDs from float to int (judge_case_merge_key)

In [33]:
judge_case_merge_key['ddl_filing_judge_id'] = pd.to_numeric(
    judge_case_merge_key['ddl_filing_judge_id'], errors='coerce'
).astype('Int64')

judge_case_merge_key['ddl_decision_judge_id'] = pd.to_numeric(
    judge_case_merge_key['ddl_decision_judge_id'], errors='coerce'
).astype('Int64')

In [34]:
judge_case_merge_key

                       ddl_case_id  ddl_filing_judge_id  ddl_decision_judge_id
0         01-01-01-201900000022018                    5                      5
1         01-01-01-201900000032017                    5                      5
2         01-01-01-201900000032018                   94                     94
3         01-01-01-201900000042016                    3                      5
4         01-01-01-201900000042018                  156                    156
...                            ...                  ...                    ...
12901141  30-02-06-203500000292016                 <NA>                  98408
12901142  30-02-06-203500000302016                 <NA>                  98427
12901143  30-02-06-203500000322016                 <NA>                  98462
12901144  30-02-06-203500000342016                 <NA>                  98427
12901145  30-02-06-203600001332016                 <NA>                  98408

[12901146 rows x 3 columns]

### 2. Formatting dates in judges_clean

In [35]:
# Convert dates to datetime
judges_clean['start_date'] = pd.to_datetime(
    judges_clean['start_date'],
    format='%d-%m-%Y',
    errors='coerce'
)

judges_clean['end_date'] = pd.to_datetime(
    judges_clean['end_date'],
    format='%d-%m-%Y',
    errors='coerce'
)

In [36]:
judges_clean['start_date']

0       2013-09-20
1       2013-10-31
2       2014-02-21
3       2016-06-01
4       2016-06-06
           ...
98473   2004-04-21
98474   2015-01-16
98475   2016-12-09
98476   2017-05-15
98477   2019-01-28
Name: start_date, Length: 98478, dtype: datetime64[us]

### 3. Code columns in key tables - STR to INT

In [37]:
cases_state_key['state_code'] = pd.to_numeric(cases_state_key['state_code'], errors='coerce').astype('Int64')

cases_district_key['state_code'] = pd.to_numeric(cases_district_key['state_code'], errors='coerce').astype('Int64')
cases_district_key['dist_code'] = pd.to_numeric(cases_district_key['dist_code'], errors='coerce').astype('Int64')

cases_court_key['state_code'] = pd.to_numeric(cases_court_key['state_code'], errors='coerce').astype('Int64')
cases_court_key['dist_code'] = pd.to_numeric(cases_court_key['dist_code'], errors='coerce').astype('Int64')
cases_court_key['court_no'] = pd.to_numeric(cases_court_key['court_no'], errors='coerce').astype('Int64')

judges_clean['state_code'] = pd.to_numeric(judges_clean['state_code'], errors='coerce').astype('Int64')
judges_clean['dist_code'] = pd.to_numeric(judges_clean['dist_code'], errors='coerce').astype('Int64')
judges_clean['court_no'] = pd.to_numeric(judges_clean['court_no'], errors='coerce').astype('Int64')

In [38]:
judge_case_merge_key

                       ddl_case_id  ddl_filing_judge_id  ddl_decision_judge_id
0         01-01-01-201900000022018                    5                      5
1         01-01-01-201900000032017                    5                      5
2         01-01-01-201900000032018                   94                     94
3         01-01-01-201900000042016                    3                      5
4         01-01-01-201900000042018                  156                    156
...                            ...                  ...                    ...
12901141  30-02-06-203500000292016                 <NA>                  98408
12901142  30-02-06-203500000302016                 <NA>                  98427
12901143  30-02-06-203500000322016                 <NA>                  98462
12901144  30-02-06-203500000342016                 <NA>                  98427
12901145  30-02-06-203600001332016                 <NA>                  98408

[12901146 rows x 3 columns]

ddl_case_id will be the primary key since no duplicates and nulls

In [31]:
judge_case_merge_key['ddl_case_id'].duplicated().sum()

np.int64(0)

# Export All Cleaned Keys to processed/export

In [39]:
from pathlib import Path

export_dir = Path(r"C:\Users\HP\OneDrive\Desktop\Projects\Judicial_DA\processed\export")
export_dir.mkdir(parents=True, exist_ok=True)

# Export all cleaned key tables
cases_state_key.to_csv(export_dir / "cases_state_key_cleaned.csv", index=False)
cases_district_key.to_csv(export_dir / "cases_district_key_cleaned.csv", index=False)
cases_court_key.to_csv(export_dir / "cases_court_key_cleaned.csv", index=False)
disp_name_key.to_csv(export_dir / "disp_name_key_cleaned.csv", index=False)
purpose_name_key.to_csv(export_dir / "purpose_name_key_cleaned.csv", index=False)
type_name_key.to_csv(export_dir / "type_name_key_cleaned.csv", index=False)
judge_case_merge_key.to_csv(export_dir / "judge_case_merge_key_cleaned.csv", index=False)
judges_clean.to_csv(export_dir / "judges_cleaned.csv", index=False)

print("✓ All cleaned keys exported to processed/export/")

✓ All cleaned keys exported to processed/export/

In [45]:
from pathlib import Path

export_dir = Path(r"C:\Users\HP\OneDrive\Desktop\Projects\Judicial_DA\processed\export")
export_dir.mkdir(parents=True, exist_ok=True)

type_name_key.to_csv(export_dir / "type_name_key_cleaned.csv", index=False)